from pydantic import BaseModel, Field, HttpUrl


class WebsiteSummaryResponse(BaseModel):
    """Structured response for the website scraper endpoint."""

    url: HttpUrl
    summary: str = Field(description="Markdown summary generated by the LLM")
